#%RAML 1.0
title: Board Experience API
version: v1
protocols: 
  - HTTP
  - HTTPS
mediaType: application/json

securitySchemes:  
  basic:  
    description: This API supports Basic Authentication
    type: Basic Authentication

traits:
  pageable:
    queryParameters:
      page:                             
        displayName: The Page Number of the list of Records
        type: number
        format: int
        required: true           
      limit:                    
        displayName: Number of Records present in each Page
        type: number
        format: int
        required: true
      format:
        enum:
          - CSV
          - JSON
        required: false
        default: JSON

/health:  
  get:  
    displayName: Get Health
    description: Return message to indicate the experience health status
    responses: 
      200: 
        body: 
          application/json: 
            example: !include examples/health-example.json

/mappings: 
  /trigger-board-child-parent-sites:
    get:
      securedBy:
        - basic          
      displayName: Child Parent Sites Mapping
      description: Retrieves Mapping from Board
      responses: 
        202: 
          body: 
            application/json: 
              example: !include examples/mapping-child-parent-sites-response.json
/reports:    
  /trial-balance:
    get:
      is:
        - pageable
      securedBy:
        - basic          
      displayName: Finance Trial Balance
      description: Retrieves Trial Balance data from the Financial Process API
      queryParameters:
        year:
          displayName: GL Balance Year
          type: number
          format: int
          required: true
        period: 
          displayName: GL Balance year's month
          type: number
          format: int
          required: true
      responses: 
        200: 
          body: 
            application/json: 
              example: !include examples/trial-balance-api-example.json
    /transactions:  
      get:  
        is:
          - pageable
        securedBy: 
          - basic
        displayName: Finance Transactions
        description: Retrieves transactions data from the Financial Process API
        queryParameters:  
          source-system:  
            type: array
            items:  
              enum: 
                - CEDS
                - MP
                - EMS
              displayName: The Source System - Permutations of [CEDS, MP, EMS]
            required: true
          reporting-unit:  
            displayName: The Reporting Unit
            type: string
            required: false
          ic-related-parties:
            displayName: IC and Related Parties
            type: string
            required: false
          year: 
            displayName: The Fiscal year
            type: number
            format: int
            required: true
          object-code:  
            type: array
            displayName: The Object Code
            required: true
        responses:  
          200:  
            body:  
              application/json:  
                example: !include examples/transactions-example.json
